name: Clone Counter

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update clone count
        uses: jgehrcke/github-repo-stats@latest
        with:
          repository: RohitYadav34980/LegacyGraph-MCP
